name: Auto-Scrape Awesome Lists

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC; adjust as needed (e.g., '*/30 * * * *' for every 30 min)
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Matches the scraper's needs

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper to update data
        run: python awesome_scraper.py  # Assumes the scraper script is in the root; move if needed

      - name: Commit and push updated data
        run: |
          git config user.name "Automated Scraper"
          git config user.email "actions@github.com"
          git add data/  # Or wherever the output JSON/files are saved (e.g., extension/data/sites.json)
          git commit -m "Auto-update scraped content: $(date -u)" || exit 0  # Skips if no changes
          git push
